spring:
  application:
    name: discovery-service
server:
  port: 8761  # discovery service 는 일반적으로 8761 포트를 사용

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0  # 레지스리가 비어있는 경우에 클라이언트가 n초 후에 재시도를 할 수 있도록 설정하는 부분. 개발서버라 0으로 설정